var localization = {
        en: {
            "Color": "Color",
            "Opacity": "Opacity",
            "Angle": "Angle",
            "Distance": "Distance",
            "Spread": "Spread",
            "Size": "Size",
            "DropShadow": "Drop Shadow",
            "InnerShadow": "Inner Shadow",
            "Background": "Background",
            "Border": "Border",
            "new": "new",
            "current": "current",
            "PickAColor": "Pick a Color",
            "GradientEditor": "Gradient Editor",
            "Ok": "Ok",
            "Cancel": "Cancel",
            "NewStyle": "New Style",
            "ColorSwatchName": "Color Swatch Name",
            "ClosestValueInserted": "Closest value inserted",
            "AnIntegerBetween": "An integer between",
            "and": "and",
            "isRequired": "is required",
            "Custom": "Custom",
            "DeleteStyle": "Delete Style"
        },
        de: {
            "Color": "Farbe",
            "Opacity": "Transparenz",
            "Angle": "Winkel",
            "Distance": "Abstand",
            "Spread": "Umfang",
            "Size": "Größe",
            "DropShadow": "Schlagschatten",
            "InnerShadow": "Innerer Schatten",
            "Background": "Hintergrund",
            "Border": "Rahmen",
            "new": "neu",
            "current": "momentan",
            "PickAColor": "Wähl eine Farbe",
            "GradientEditor": "Verlaufs Editor",
            "Ok": "Ok",
            "Cancel": "Abbrechen",
            "NewStyle": "Neuer Style",
            "ColorSwatchName": "Farbfeld Name",
            "ClosestValueInserted": "Naheliegendste Zahl eingesetzt",
            "AnIntegerBetween": "Eine Zahl zwischen",
            "and": "und",
            "isRequired": "wird benötigt",
            "Custom": "Unbekannt",
            "DeleteStyle": "Style löschen"
        }
}